"repositories for java"

#VERSION 21.0.11

java = use_extension("//private/extensions:java.bzl", "java")
java.archive(
    name = "temurin21_jre_amd64",
    sha256 = "e5038aae3ca9ff670bc696496b0728dbd23d280026bad30291cb919221ecfdcb",
    strip_prefix = "jdk-21.0.11+10-jre",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jre_x64_linux_hotspot_21.0.11_10.tar.gz"],
    version = "21.0.11+10",
    plain_version = "21.0.11",
    architecture = "amd64",
)
java.archive(
    name = "temurin21_jdk_amd64",
    sha256 = "4b2220e232a97997b436ca6ab15cbf70171ecff52958a46159dfa5a8c44ca4de",
    strip_prefix = "jdk-21.0.11+10",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jdk_x64_linux_hotspot_21.0.11_10.tar.gz"],
    version = "21.0.11+10",
    plain_version = "21.0.11",
    architecture = "amd64",
)
java.archive(
    name = "temurin21_jre_arm64",
    sha256 = "fa23d9d9945053e67bcc7638410eabf1e17a7672c7c95a24f70cd08b8407d36e",
    strip_prefix = "jdk-21.0.11+10-jre",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jre_aarch64_linux_hotspot_21.0.11_10.tar.gz"],
    version = "21.0.11+10",
    plain_version = "21.0.11",
    architecture = "arm64",
)
java.archive(
    name = "temurin21_jdk_arm64",
    sha256 = "8d498ec88e1c1989fab95c6784240ab92d011e29c54d20a3f9c324b13476f9ad",
    strip_prefix = "jdk-21.0.11+10",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jdk_aarch64_linux_hotspot_21.0.11_10.tar.gz"],
    version = "21.0.11+10",
    plain_version = "21.0.11",
    architecture = "arm64",
)
java.archive(
    name = "temurin21_jre_ppc64le",
    sha256 = "fefb53c4bd687e7a91a9a9809ec80e0862e829cd20513839ad1a9988ddc89482",
    strip_prefix = "jdk-21.0.11+10-jre",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jre_ppc64le_linux_hotspot_21.0.11_10.tar.gz"],
    version = "21.0.11+10",
    plain_version = "21.0.11",
    architecture = "ppc64le",
)
java.archive(
    name = "temurin21_jdk_ppc64le",
    sha256 = "3d043ae96d2343962bf2307d8c55f19849fbfa4c6be9fe164a77d79263f0d989",
    strip_prefix = "jdk-21.0.11+10",
    urls = ["https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.11%2B10/OpenJDK21U-jdk_ppc64le_linux_hotspot_21.0.11_10.tar.gz"],
    version = "21.0.11+10",
    plain_version = "21.0.11",
    architecture = "ppc64le",
)
use_repo(java, "java_versions", "temurin21_jdk_amd64", "temurin21_jdk_arm64", "temurin21_jdk_ppc64le", "temurin21_jre_amd64", "temurin21_jre_arm64", "temurin21_jre_ppc64le")
